// Manual mock for kolmafia module that may not be installed
module.exports = {
  getMonsters: jest.fn(),
  myAdventures: jest.fn(() => 100),
  myFamiliar: jest.fn(() => ({})),
  buy: jest.fn(),
  canEquip: jest.fn(() => true),
  effectModifier: jest.fn(() => 0),
  equippedItem: jest.fn(() => ({})),
  Familiar: { all: jest.fn(() => []) },
  fullnessLimit: jest.fn(() => 15),
  getOutfits: jest.fn(() => []),
  haveEquipped: jest.fn(() => false),
  inebrietyLimit: jest.fn(() => 5),
  Item: { all: jest.fn(() => []) },
  mallPrice: jest.fn(() => 100),
  myEffects: jest.fn(() => ({})),
  myFullness: jest.fn(() => 0),
  myInebriety: jest.fn(() => 0),
  numericModifier: jest.fn(() => 0),
  outfitPieces: jest.fn(() => []),
  outfitTreats: jest.fn(() => ({})),
  Slot: { all: jest.fn(() => []) },
  toEffect: jest.fn((name) => ({ name })),
  toItem: jest.fn((name) => ({ name })),
  toJson: jest.fn((obj) => JSON.stringify(obj)),
  toSlot: jest.fn((name) => ({ name })),
  totalTurnsPlayed: jest.fn(() => 0),
  userConfirm: jest.fn(() => true),
  abort: jest.fn(),
};